import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
await fs.mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.DEMO_URL||'http://127.0.0.1:8124');
await page.waitForFunction(()=>window.robotLab,{timeout:120000});
await page.waitForTimeout(2500);
await page.screenshot({path:'artifacts/desktop.png'});
await page.locator('#play').click();
await page.waitForTimeout(100);
const paused=await page.evaluate(()=>window.robotLab.snapshot());
await page.waitForTimeout(300);
assert.equal((await page.evaluate(()=>window.robotLab.snapshot())).time,paused.time);
assert.equal(await page.locator('.joint-chart canvas').count(),3);
assert.ok(paused.telemetry.count>1);
assert.deepEqual((await page.evaluate(()=>window.robotLab.snapshot())).telemetry,paused.telemetry);
assert.equal(paused.telemetry.last.arms[0].position.length,6);
await page.locator('.joint-settings summary').click();
await page.locator('#joint-0').fill('-45');await page.locator('#joint-0').dispatchEvent('input');
assert.ok(Math.abs((await page.evaluate(()=>window.robotLab.snapshot())).target[0]+Math.PI/4)<.001);
await page.locator('#play').click();await page.waitForTimeout(1500);
assert.ok(Math.abs((await page.evaluate(()=>window.robotLab.snapshot())).qpos[0]-paused.qpos[0])>.1);
await page.locator('[data-pose="reach"]').click();
assert.equal((await page.evaluate(()=>window.robotLab.snapshot())).target[0],-1.57);
await page.locator('[data-arm="1"]').click();
await page.waitForFunction(()=>window.robotLab.snapshot().telemetry.arm===1);
assert.equal(await page.locator('#telemetry-arm').textContent(),'오른팔');
const beforeRight=await page.evaluate(()=>window.robotLab.snapshot());
await page.locator('#joint-0').fill('-80');await page.locator('#joint-0').dispatchEvent('input');
const afterRight=await page.evaluate(()=>window.robotLab.snapshot());
assert.equal(afterRight.target[0],beforeRight.target[0]);
assert.ok(Math.abs(afterRight.target[7]+80*Math.PI/180)<.001);
await page.locator('#gripper').fill('0');await page.locator('#gripper').dispatchEvent('input');
assert.equal((await page.evaluate(()=>window.robotLab.snapshot())).target[13],0);
await page.locator('#linked').check();await page.locator('[data-pose="folded"]').click();
const linked=await page.evaluate(()=>window.robotLab.snapshot());
assert.deepEqual(linked.target.slice(0,6),linked.target.slice(7,13));
await page.locator('#demo').click();await page.waitForTimeout(200);
assert.equal((await page.evaluate(()=>window.robotLab.snapshot())).demo,true);
await page.locator('#play').click();
await page.locator('#reset').click();
const reset=await page.evaluate(()=>window.robotLab.snapshot());
assert.equal(reset.telemetry.count,1);
assert.equal(reset.telemetry.last.time,0);
assert.equal((await page.evaluate(()=>window.robotLab.snapshot())).demo,false);
await page.locator('#axes').uncheck();await page.locator('#trail').uncheck();await page.locator('#camera').click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile overflow');
assert.deepEqual(errors,[]);
console.log('PASS: browser WASM load, pause/resume, slider, preset, demo, reset, toggles, responsive layout, 3 six-axis charts, history pause/reset/arm selection, no JS errors.');
await browser.close();
