import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
await fs.mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.DEMO_URL||'http://127.0.0.1:8124');
await page.waitForFunction(()=>window.robotLab,{timeout:120000});
await page.waitForTimeout(2500);
await page.screenshot({path:'artifacts/desktop.png'});
await page.locator('#play').click();
await page.waitForTimeout(100);
const paused=await page.evaluate(()=>window.robotLab.snapshot());
await page.waitForTimeout(300);
assert.equal((await page.evaluate(()=>window.robotLab.snapshot())).time,paused.time);
await page.locator('#joint-0').fill('-45');await page.locator('#joint-0').dispatchEvent('input');
assert.ok(Math.abs((await page.evaluate(()=>window.robotLab.snapshot())).target[0]+Math.PI/4)<.001);
await page.locator('#play').click();await page.waitForTimeout(1500);
assert.ok(Math.abs((await page.evaluate(()=>window.robotLab.snapshot())).qpos[0]-paused.qpos[0])>.1);
await page.locator('[data-pose="reach"]').click();
assert.equal((await page.evaluate(()=>window.robotLab.snapshot())).target[0],-.65);
await page.locator('#demo').click();await page.waitForTimeout(200);
assert.equal((await page.evaluate(()=>window.robotLab.snapshot())).demo,true);
await page.locator('#reset').click();
assert.equal((await page.evaluate(()=>window.robotLab.snapshot())).demo,false);
await page.locator('#axes').uncheck();await page.locator('#trail').uncheck();await page.locator('#camera').click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile overflow');
assert.deepEqual(errors,[]);
console.log('PASS: browser WASM load, pause/resume, slider, preset, demo, reset, toggles, responsive layout, no JS errors.');
await browser.close();
